### ISSUE TITLE
Net::OpenTimeout: execution expired

### ISSUE THREAD

**Issue by yegor256** [yegor256/0rsk#54]
```
Net::OpenTimeout: execution expired
  from net/http.rb:947:in `initialize'
  from net/http.rb:947:in `open'
  from net/http.rb:947:in `block in connect'
  from timeout.rb:103:in `timeout'
  from net/http.rb:945:in `connect'
  from net/http.rb:930:in `do_start'
  from net/http.rb:919:in `start'
  from net/http.rb:1470:in `request'
  from faraday/adapter/net_http.rb:87:in `perform_request'
  from faraday/adapter/net_http.rb:43:in `block in call'
  from faraday/adapter/net_http.rb:92:in `with_net_http_connection'
  from faraday/adapter/net_http.rb:38:in `call'
  from faraday_middleware/response_middleware.rb:31:in `call'
  from faraday/request/url_encoded.rb:15:in `call'
  from faraday/request/multipart.rb:15:in `call'
  from faraday/rack_builder.rb:143:in `build_response'
  from faraday/connection.rb:387:in `run_request'
  from faraday/connection.rb:175:in `post'
  from telebot/client.rb:219:in `call'
  from telebot/client.rb:51:in `get_updates'
  from telebot/bot.rb:19:in `block in run'
  from telebot/bot.rb:15:in `loop'
  from telebot/bot.rb:15:in `run'
  from front/front_telegram.rb:136:in `block in <top (required)>'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.7.3`

**Comment by 0crat** [comment]
Job `gh:yegor256/0rsk#54` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
